name: transformer_htr

image_channels: 1
image_height: 64

hidden_size: 512
encoder_layers: 2
decoder_layers: 2
nhead: 4
dim_feedforward: 2048
dropout: 0.2

pad_idx: 0
sos_idx: 1
eos_idx: 2
max_decoding_length: 100

scheduler:
  enabled: true
  monitor: val_loss
  mode: min
  factor: 0.5
  patience: 5
